### ISSUE TITLE
issue with get event detials

### ISSUE THREAD

**Issue by samroberts93** [ticketmaster-api/sdk-ruby#1]
Hi there

Trying to use this with event id being this 37004F55AD5AB898 and it returns this error

"detail"=>"Resource not found with provided criteria (locale=en, id=37004F55AD5AB898)"

Wondering if its this or ticketmasters error

Sam

**Comment by connerfritz** [comment]
Hi @samroberts93 

Unfortunately the IDs  used by the Discovery API are different than those used on Ticketmaster.co.uk and other sites.

For that Event, I believe the ID is `G5djZKgpcplxb` if that helps.

I'll investigate if there are ways to get Discovery API events via Ticketmaster.co.uk IDs and look into changing the error/missing even handling to make things clearer.

Thanks!

Conner

**Comment by samroberts93** [comment]
@connerfritz Your right, That id's correct too If you could that'd be super sick!! If not then theres no worries :) 👍

**Comment by connerfritz** [comment]
@samroberts93 I have updated the gem and it now features the Ticketmaster API Legacy endpoint.

To use Ticketmaster.com IDs, just use the `get_legacy_event` method on the client:

```
require 'ticketmaster-sdk'

client = Ticketmaster.client(apikey: 'YOUR API KEY')
event = client.get_legacy_event('37004F55AD5AB898')
```

Documentation has been updated with the addition.
