### ISSUE TITLE
Event Prices for UK Events

### ISSUE THREAD

**Issue by samnymr** [ticketmaster-api/sdk-ruby#2]
Hi there

Could i quickly ask (ITs not an issue with the gem more the api) How long until Ticketmaster prices will be shown in the api. And will it include fees? If not what is the fee algorithm?

Thanks

**Comment by connerfritz** [comment]
I believe the Commerce API currently shows prices, but this gem doesn't yet support it. I'm hoping to add support for it in the next update.

http://developer.ticketmaster.com/products-and-docs/apis/commerce/
