### ISSUE TITLE
city, stateCode, countryCode not permitted params

### ISSUE THREAD

**Issue by stowns** [ticketmaster-api/sdk-ruby#3]
city, stateCode and countryCode are listed as valid params in the documentation but are stripped if passed to a request.

https://github.com/ticketmaster-api/sdk-ruby/blob/0e37db1fcb276e8a65ccf98f9583c87afda4110f/lib/ticketmaster/configuration.rb

_docs_
http://developer.ticketmaster.com/products-and-docs/apis/discovery/v2/#srch-events-v2

**Comment by connerfritz** [comment]
Looks like some fields were added, thanks for pointing this out! Fixed in 0.0.05. (https://github.com/ticketmaster-api/sdk-ruby/commit/63b939d8860dba23fd31d7c74c7706b76da67752)
