### ISSUE TITLE
Searching for events by attraction_id errors if there are no events

### ISSUE THREAD

**Issue by Genkilabs** [ticketmaster-api/sdk-ruby#4]
The events response no longer includes the key ```data['_embedded']``` if there are no events found. This means the example if you do this
```
response = client.search_events(params: params)
events = response.results
```
Will raise an error like
```
2.2.3 :046 >   response.results
NoMethodError: undefined method `[]' for nil:NilClass
	from /Users/gingitsune/.rvm/gems/ruby-2.2.3/gems/ticketmaster-sdk-0.0.05/lib/ticketmaster/results/search.rb:6:in `results'
	from (irb):46
	from /Users/gingitsune/.rvm/rubies/ruby-2.2.3/bin/irb:11:in `<main>'
```

It comes from here: https://github.com/ticketmaster-api/sdk-ruby/blob/0afec6296692247b9fe7d85d5f4b24a4748a23c8/lib/ticketmaster/results/search.rb#L6

It just needs to have a check for ```response.data['page']['totalElements'] > 0``` or something to return [].

Is this repo still maintained? I see no code changes for 2 years. If I fix it and make a PR will anyone answer?

**Comment by connerfritz** [comment]
I know it's been a long time since this issue was opened, but I merged a fix today and added a test to cover this case.

**Comment by Genkilabs** [comment]
Great, thank you! 
We ended up with some workaround in production (I forget what), but our roadmap includes TM stuff this summer so we may end up revisiting this.
